### ISSUE TITLE
CurrId does not persist

### ISSUE THREAD

**Issue by LucyWilcox** [LucyWilcox/mushroomspores#2]
It seems that currrid get reset to 1. Perhaps each morning.

Update: it's not happening each day. It seems to be happening when the heroku app shuts down after a period of inactivity and starts up again from a new visitor.

**Comment by JimmyFW** [comment]
Ok so now we'll gotta set up heroku postgres, and once that's done, do this: http://killtheyak.com/use-postgresql-with-django-flask/

**Comment by jwjimmy** [comment]
http://initd.org/psycopg/docs/usage.html

**Comment by jwjimmy** [comment]
:haircut: :hamburger:
